import { PrismaClient, ContentStatus, ContentSource } from '@prisma/client'

const prisma = new PrismaClient()

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .substring(0, 80)
}

function inferCategory(tags: string, title: string): string {
  const combined = (tags + ' ' + title).toLowerCase()
  if (combined.includes('rpg') || combined.includes('adventure') || combined.includes('dungeon') || combined.includes('quest')) return 'rpg'
  if (combined.includes('chat') || combined.includes('companion') || combined.includes('roleplay') || combined.includes('character')) return 'chat'
  if (combined.includes('puzzle') || combined.includes('riddle') || combined.includes('escape') || combined.includes('logic')) return 'puzzle'
  if (combined.includes('simulation') || combined.includes('simulator') || combined.includes('world') || combined.includes('manage')) return 'simulation'
  if (combined.includes('language') || combined.includes('learn') || combined.includes('education')) return 'education'
  if (combined.includes('story') || combined.includes('visual novel') || combined.includes('narrative') || combined.includes('fiction')) return 'story'
  if (combined.includes('strategy') || combined.includes('tactical') || combined.includes('combat')) return 'strategy'
  if (combined.includes('sandbox') || combined.includes('crafting') || combined.includes('create') || combined.includes('open world')) return 'sandbox'
  if (combined.includes('discovery') || combined.includes('directory') || combined.includes('hub') || combined.includes('collection') || combined.includes('curated') || combined.includes('list')) return 'discovery'
  if (combined.includes('social') || combined.includes('multiplayer') || combined.includes('party')) return 'social'
  return 'other'
}

const games = [
  {
    title: 'AI Dungeon',
    url: 'https://aidungeon.com/',
    shortDescription: 'A text-based adventure-story game you direct while the AI brings it to life.',
    fullDescription: 'AI Dungeon is a text-based adventure game where you direct and star in AI-generated stories. The AI brings your choices to life, creating infinite possibilities across fantasy, sci-fi, mystery, and more. Play solo or with friends in multiplayer mode.',
    coverImage: 'https://images.unsplash.com/photo-1614854262318-831574f15f1f?w=400&h=300&fit=crop',
    tags: ['Text Adventure', 'RPG', 'AI-Generated Story', 'Multiplayer'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium subscription',
    featured: true,
    featuredOrder: 1,
  },
  {
    title: 'Character.AI',
    url: 'https://character.ai/',
    shortDescription: 'Talk with AI characters built by the community — celebrities, fictional characters, and more.',
    fullDescription: 'Character.AI lets you create and talk with AI characters. Chat with your favorite fictional characters, celebrities, or create your own AI persona. The platform features millions of user-created characters across every genre and interest.',
    coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=300&fit=crop',
    tags: ['AI Chat', 'Character Roleplay', 'Community'],
    platform: ['Web', 'iOS', 'Android'],
    isFree: true,
    pricingNote: 'Free + c.ai+ subscription',
    featured: true,
    featuredOrder: 2,
  },
  {
    title: 'Infinite Craft',
    url: 'https://neal.fun/infinite-craft/',
    shortDescription: 'Combine elements to create new ones in this AI-powered crafting sandbox.',
    fullDescription: 'Infinite Craft is a browser-based sandbox game where you combine elements to discover new ones. Starting with earth, wind, fire, and water, use AI to generate endless combinations. Discover everything from simple objects to abstract concepts.',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=300&fit=crop',
    tags: ['Sandbox', 'Crafting', 'Casual', 'Browser'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: true,
    featuredOrder: 3,
  },
  {
    title: 'Human or Not',
    url: 'https://humanornot.ai/',
    shortDescription: 'A social Turing game — can you tell if you\'re talking to a human or an AI?',
    fullDescription: 'Human or Not is a social Turing game where you chat with either a human or an AI for two minutes, then guess which one it was. Test your ability to distinguish between human and artificial intelligence in real conversations.',
    coverImage: 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=400&h=300&fit=crop',
    tags: ['Social', 'Turing Test', 'Multiplayer', 'Casual'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: true,
    featuredOrder: 4,
  },
  {
    title: 'Friends & Fables',
    url: 'https://fables.gg/',
    shortDescription: 'A DnD-inspired text RPG powered by AI with an AI Game Master.',
    fullDescription: 'Friends & Fables is a DnD-inspired text RPG where an AI Game Master guides your adventure. Create characters, build worlds, engage in tactical combat, and experience dynamic storylines that adapt to your choices.',
    coverImage: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=400&h=300&fit=crop',
    tags: ['RPG', 'DnD', 'AI Game Master', 'Tactical Combat', 'World Building'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Chai',
    url: 'https://chai.ml/',
    shortDescription: 'Chat with AI companions and build your own AI chatbots.',
    fullDescription: 'Chai is an AI chat platform where you can talk with AI companions or build your own chatbots. The platform features thousands of user-created AI personalities, from friendly companions to fictional characters.',
    coverImage: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=400&h=300&fit=crop',
    tags: ['AI Chat', 'Companion', 'Chatbot Builder'],
    platform: ['Web', 'iOS', 'Android'],
    isFree: true,
    pricingNote: 'Free + Chai+ subscription',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Spellbound',
    url: 'https://www.spellbound.so/',
    shortDescription: 'An AI-powered interactive fiction platform for immersive storytelling.',
    fullDescription: 'Spellbound is an interactive fiction platform powered by AI. Dive into rich narrative worlds, make choices that matter, and experience stories that adapt to your decisions in real time.',
    coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop',
    tags: ['Interactive Fiction', 'Storytelling', 'AI-Driven'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Latitude',
    url: 'https://latitude.io/',
    shortDescription: 'The platform behind AI Dungeon, creating AI-powered game experiences.',
    fullDescription: 'Latitude is the company behind AI Dungeon and other AI-powered game experiences. Their platform enables infinite AI-generated narratives and interactive storytelling across multiple genres.',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    tags: ['AI Platform', 'Game Development', 'Narrative AI'],
    platform: ['Web'],
    isFree: false,
    pricingNote: 'Subscription required',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Inworld AI',
    url: 'https://inworld.ai/',
    shortDescription: 'Create AI characters with rich personalities for games and interactive experiences.',
    fullDescription: 'Inworld AI provides tools to create AI-powered characters with rich personalities, emotions, and memories for games and interactive experiences. Build NPCs that feel truly alive.',
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=300&fit=crop',
    tags: ['AI Characters', 'NPC', 'Game Development', 'Interactive'],
    platform: ['Web'],
    isFree: false,
    pricingNote: 'Free tier + paid plans',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Rosebud AI',
    url: 'https://rosebud.ai/',
    shortDescription: 'Make your own AI games with a simple prompt — no coding required.',
    fullDescription: 'Rosebud AI lets you create your own games using simple text prompts. No coding required. The platform generates playable games from your descriptions, covering RPGs, simulations, puzzles, and more.',
    coverImage: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=300&fit=crop',
    tags: ['Game Creation', 'AI-Generated', 'No Code', 'RPG', 'Simulation'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Pro plan',
    featured: true,
    featuredOrder: 5,
  },
  {
    title: 'AI Town',
    url: 'https://ai-town.com/',
    shortDescription: 'A virtual town where AI agents live, work, and interact autonomously.',
    fullDescription: 'AI Town is a virtual world where AI agents go about their daily lives autonomously. Watch them work, socialize, and interact with each other in a simulated town environment powered by large language models.',
    coverImage: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400&h=300&fit=crop',
    tags: ['AI Simulation', 'Autonomous Agents', 'Virtual World'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Ludo AI',
    url: 'https://ludo.ai/',
    shortDescription: 'AI-powered game design and ideation platform for game developers.',
    fullDescription: 'Ludo AI is a game design platform that uses AI to help developers brainstorm, research, and design games. Generate game concepts, analyze market trends, and get AI-powered insights for your next game project.',
    coverImage: 'https://images.unsplash.com/photo-1556438064-2d7646166914?w=400&h=300&fit=crop',
    tags: ['Game Design', 'AI Tools', 'Game Development', 'Ideation'],
    platform: ['Web'],
    isFree: false,
    pricingNote: 'Free trial + subscription',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Convai',
    url: 'https://www.convai.com/',
    shortDescription: 'Build conversational AI characters for games and virtual worlds.',
    fullDescription: 'Convai enables developers to build intelligent, conversational AI characters for games and virtual worlds. Characters can understand context, remember conversations, and respond naturally to player interactions.',
    coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop',
    tags: ['Conversational AI', 'Game Characters', 'NPC', 'SDK'],
    platform: ['Web'],
    isFree: false,
    pricingNote: 'Free tier + paid plans',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Plix GG',
    url: 'https://plix.gg/',
    shortDescription: 'Discover and play AI-generated games across multiple genres.',
    fullDescription: 'Plix GG is a platform for discovering and playing AI-generated games. Browse games by tags, play directly in your browser, and explore a growing library of AI-powered gaming experiences.',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=300&fit=crop',
    tags: ['AI Games Hub', 'Browser Games', 'Discovery'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Vibe Games',
    url: 'https://vibegames.cc/',
    shortDescription: 'A collection of vibe-coded AI games built with modern AI tools.',
    fullDescription: 'Vibe Games is a curated collection of games built using AI coding tools. Browse and play a variety of AI-assisted games, from casual puzzles to creative experiences, all made by indie developers using AI.',
    coverImage: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=400&h=300&fit=crop',
    tags: ['Indie Games', 'AI-Built', 'Browser Games', 'Casual'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'AI Game Master',
    url: 'https://www.aigamemaster.app/',
    shortDescription: 'An AI-powered Dungeon Master for DnD-inspired text adventures.',
    fullDescription: 'AI Game Master is an immersive AI-powered Dungeon Master for fans of Dungeons & Dragons and tabletop RPGs. Experience dynamic campaigns, rich lore, and adaptive storytelling guided by an intelligent AI.',
    coverImage: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=400&h=300&fit=crop',
    tags: ['DnD', 'AI Game Master', 'Text Adventure', 'RPG', 'Tabletop'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Master of Lore',
    url: 'https://masteroflore.com/ai-game-master',
    shortDescription: 'AI game master platform with dynamic storylines, visuals, and ambient music.',
    fullDescription: 'Master of Lore offers a tabletop role-playing game experience powered by AI. Enjoy dynamic storylines that adapt to your choices, AI-generated visuals, and atmospheric ambient music for a fully immersive TTRPG experience.',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=300&fit=crop',
    tags: ['AI RPG', 'Game Master', 'Tabletop RPG', 'Interactive Story', 'Visual Generation'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Talefy',
    url: 'https://talefy.ai/',
    shortDescription: 'An AI story generator for creating and playing interactive stories.',
    fullDescription: 'Talefy is an AI story generator platform where you can create interactive stories or dive into AI-generated narratives. Features dynamic branching storylines, character customization, and multiple genres from romance to thriller.',
    coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop',
    tags: ['AI Story Generator', 'Interactive Story', 'Text Adventure', 'RPG'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'World Simulator AI',
    url: 'https://worldsimulator.ai/',
    shortDescription: 'Dive into immersive AI-powered virtual worlds where your choices shape the story.',
    fullDescription: 'World Simulator AI lets you explore immersive first-person AI-powered virtual worlds. Every choice you make shapes the narrative and environment, creating a unique experience powered by advanced language models.',
    coverImage: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=300&fit=crop',
    tags: ['AI Simulation', 'Interactive Story', 'First Person', 'Open World'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'ChatJitsu',
    url: 'https://chatjitsu.app/',
    shortDescription: 'A daily LLM puzzle game — master prompt engineering through AI challenges.',
    fullDescription: 'ChatJitsu is a daily puzzle game powered by ChatGPT where players master the art of prompt engineering. Solve creative challenges by crafting the perfect prompts to guide the AI to your desired outcome.',
    coverImage: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=300&fit=crop',
    tags: ['LLM Puzzle', 'Prompt Engineering', 'Daily Challenge', 'Casual'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'AI Escape',
    url: 'https://rooms.aiescape.io/',
    shortDescription: 'AI-generated escape rooms with endless possibilities and personalized challenges.',
    fullDescription: 'AI Escape uses advanced AI to generate customized escape rooms with endless possibilities. Each room features immersive storylines and personalized challenges that adapt to your skill level and choices.',
    coverImage: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=400&h=300&fit=crop',
    tags: ['Escape Room', 'AI-Generated', 'Puzzle', 'Immersive'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Infinite Worlds',
    url: 'https://infiniteworlds.app/',
    shortDescription: 'AI-powered adventures with unlimited freedom, stories, and illustrations.',
    fullDescription: 'Infinite Worlds offers unlimited freedom in AI-powered adventures. Craft your own stories or dive into unique narratives powered by cutting-edge AI, complete with AI-generated illustrations that bring your world to life.',
    coverImage: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400&h=300&fit=crop',
    tags: ['AI RPG', 'Text Adventure', 'AI Art', 'Interactive Story', 'Free'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Oasis',
    url: 'https://oasis-model.github.io/',
    shortDescription: 'The first real-time open-world AI model — an interactive video experience entirely generated by AI.',
    fullDescription: 'Oasis is a groundbreaking AI model that generates an interactive open-world experience in real time. Every frame is generated by AI, creating a unique video game-like experience that pushes the boundaries of generative AI.',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    tags: ['AI World', 'Real-Time Generation', 'Interactive Video', 'Research'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: true,
    featuredOrder: 6,
  },
  {
    title: 'Depthtale',
    url: 'https://www.depthtale.com/en',
    shortDescription: 'A new generation of visual novels blending traditional storytelling with interactive exploration.',
    fullDescription: 'Depthtale offers a new generation of visual novels that combine traditional narrative storytelling with interactive exploration. Experience rich, branching stories with beautiful visuals and meaningful choices.',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=300&fit=crop',
    tags: ['Visual Novel', 'Interactive Story', 'Adventure', 'Narrative'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Jenova AI',
    url: 'https://jenova.ai/',
    shortDescription: 'AI-powered language learning through immersive roleplay scenarios.',
    fullDescription: 'Jenova AI teaches languages through immersive roleplay scenarios. Learn Spanish, French, Korean, and more through authentic conversations with AI characters in culturally rich settings, from Parisian cafés to Seoul streets.',
    coverImage: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&h=300&fit=crop',
    tags: ['Language Learning', 'Roleplay', 'Education', 'AI Conversation'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Dreamrunner',
    url: 'https://app.dreamrunner.ai/',
    shortDescription: 'Interactive AI-powered story experiences with rich narrative worlds.',
    fullDescription: 'Dreamrunner offers interactive AI-powered story experiences where you become the protagonist. Explore richly crafted narrative worlds, make choices that shape the story, and experience adventures that adapt to your decisions.',
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400&h=300&fit=crop',
    tags: ['Interactive Story', 'AI Narrative', 'Adventure', 'Fantasy'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Suck Up',
    url: 'https://www.suckupgame.com/',
    shortDescription: 'Convince AI-powered villagers to let you into their homes as a vampire.',
    fullDescription: 'Suck Up is a hilarious AI-powered game where you play as a vampire trying to convince villagers to invite you inside. Each NPC is powered by AI and responds uniquely to your persuasion attempts — be creative!',
    coverImage: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=400&h=300&fit=crop',
    tags: ['Comedy', 'AI NPC', 'Persuasion', 'Casual', 'Unique'],
    platform: ['Web', 'PC'],
    isFree: false,
    pricingNote: 'Paid game',
    featured: true,
    featuredOrder: 7,
  },
  {
    title: 'Macko AI',
    url: 'https://www.macko.ai/',
    shortDescription: 'AI-powered interactive game experiences with dynamic characters.',
    fullDescription: 'Macko AI delivers interactive game experiences powered by advanced AI. Engage with dynamic characters, explore branching narratives, and enjoy personalized gameplay that responds to your unique style.',
    coverImage: 'https://images.unsplash.com/photo-1535223289429-462ea9301402?w=400&h=300&fit=crop',
    tags: ['AI Games', 'Interactive', 'Dynamic Characters'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Reblin',
    url: 'https://www.reblin.co/',
    shortDescription: 'AI-powered social deduction and mystery games.',
    fullDescription: 'Reblin offers AI-powered social deduction and mystery games. Work with or against AI players, uncover secrets, and solve mysteries in dynamic game scenarios that change every playthrough.',
    coverImage: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=300&fit=crop',
    tags: ['Social Deduction', 'Mystery', 'AI Players', 'Multiplayer'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Grok Games',
    url: 'https://www.grokgames.gg/',
    shortDescription: 'A collection of AI-powered games built with Grok AI.',
    fullDescription: 'Grok Games is a collection of games powered by Grok AI. Experience unique gameplay mechanics enabled by xAI\'s Grok model, from conversational adventures to AI-driven puzzle experiences.',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=300&fit=crop',
    tags: ['Grok AI', 'AI Games', 'xAI', 'Browser Games'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Pilab AI Games',
    url: 'https://pilab.dev/ai-game-collection',
    shortDescription: 'A curated collection of AI-powered games from Pilab.',
    fullDescription: 'Pilab Dev hosts a curated collection of AI-powered games. Explore a variety of browser-based games that leverage AI for unique gameplay experiences, from generative puzzles to interactive stories.',
    coverImage: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=300&fit=crop',
    tags: ['AI Game Collection', 'Browser Games', 'Indie', 'Curated'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Genie 3',
    url: 'https://genie3.site/gallery',
    shortDescription: 'AI-generated interactive game worlds from Google DeepMind\'s Genie 3.',
    fullDescription: 'Genie 3 is a research project from Google DeepMind that generates interactive game worlds from text or image prompts. Explore AI-generated environments and interact with them in real time.',
    coverImage: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=300&fit=crop',
    tags: ['AI World Generation', 'DeepMind', 'Research', 'Interactive'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: true,
    featuredOrder: 8,
  },
  {
    title: 'AI Built Games',
    url: 'https://aibuiltgames.com/',
    shortDescription: 'A showcase of games built entirely by AI.',
    fullDescription: 'AI Built Games is a showcase platform for games created entirely using AI tools. Discover what\'s possible when AI handles game design, art, code, and narrative — a glimpse into the future of game development.',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    tags: ['AI-Built', 'Showcase', 'Indie Games', 'AI Development'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Dang AI Games',
    url: 'https://dang.ai/category/ai-games-list',
    shortDescription: 'Discover the best AI games curated by the Dang.ai community.',
    fullDescription: 'Dang.ai is a community-curated directory of the best AI tools and games. The AI Games category features top-rated games voted on by the community, spanning every genre from RPG to puzzle to simulation.',
    coverImage: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=400&h=300&fit=crop',
    tags: ['AI Games Directory', 'Community Curated', 'Discovery'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Itch.io AI Games',
    url: 'https://itch.io/c/3543695/ai-games',
    shortDescription: 'A curated collection of AI games on the indie game platform itch.io.',
    fullDescription: 'Itch.io hosts thousands of indie games, including a growing collection of AI-powered games. This curated list features the best AI games on the platform, from experimental art games to full AI-driven RPGs.',
    coverImage: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=300&fit=crop',
    tags: ['Indie Games', 'Itch.io', 'AI Games', 'Curated'],
    platform: ['Web', 'PC', 'Mac'],
    isFree: true,
    pricingNote: 'Varies by game',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Aixploria AI Games',
    url: 'https://www.aixploria.com/en/category/games-en/',
    shortDescription: 'Explore the best AI games curated by Aixploria.',
    fullDescription: 'Aixploria is a comprehensive directory of AI tools and games. Their games category features a curated selection of the best AI-powered gaming experiences available, updated regularly with new discoveries.',
    coverImage: 'https://images.unsplash.com/photo-1535223289429-462ea9301402?w=400&h=300&fit=crop',
    tags: ['AI Directory', 'Games', 'Curated', 'Discovery'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Free AI Games',
    url: 'https://freeai.games/',
    shortDescription: 'Play free AI-powered games directly in your browser.',
    fullDescription: 'Free AI Games is a platform dedicated to free AI-powered browser games. No downloads, no subscriptions — just click and play. Features a growing library of games across multiple genres all powered by AI.',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=300&fit=crop',
    tags: ['Free Games', 'Browser Games', 'AI-Powered', 'No Signup'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Gamelist AI',
    url: 'https://gamelist.ai/',
    shortDescription: 'Discover and play the best AI-generated games.',
    fullDescription: 'Gamelist AI is a curated directory of the best AI-generated and AI-powered games. Browse by category, read reviews, and discover your next favorite AI game experience.',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    tags: ['AI Games Directory', 'Discovery', 'Reviews', 'Curated'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Gameer IO',
    url: 'https://www.gameer.io/',
    shortDescription: 'Play AI-powered games and discover new AI gaming experiences.',
    fullDescription: 'Gameer.io is a platform for discovering and playing AI-powered games. Features a curated selection of browser-based AI games with ratings, reviews, and community features.',
    coverImage: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=300&fit=crop',
    tags: ['AI Games', 'Browser Games', 'Community', 'Discovery'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'AI Game Hub Space',
    url: 'https://www.aigamehub.space/',
    shortDescription: 'A hub for AI game discovery and play.',
    fullDescription: 'AI Game Hub Space is a dedicated platform for discovering and playing AI-powered games. Browse a curated collection of AI games, read descriptions, and launch games directly from the hub.',
    coverImage: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=400&h=300&fit=crop',
    tags: ['AI Games Hub', 'Discovery', 'Browser Games'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Flat AI Games',
    url: 'https://flatai.org/free-ai-rpg-games-no-signup-instant-play-adventures/',
    shortDescription: 'Free AI RPG games with no signup required — instant play adventures.',
    fullDescription: 'Flat AI Games offers free AI-powered RPG adventures with no signup required. Jump straight into AI-generated stories and explore infinite worlds without any barriers to entry.',
    coverImage: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=400&h=300&fit=crop',
    tags: ['Free RPG', 'No Signup', 'Instant Play', 'AI Adventure'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'LLM Riddles',
    url: 'https://apps.apple.com/au/app/llm-riddles/id6517349464',
    shortDescription: 'The ultimate AI puzzle challenge — runs entirely offline on your device.',
    fullDescription: 'LLM Riddles brings cutting-edge language model technology to your iOS device. Solve AI-powered riddles and puzzles entirely offline, with no internet required. Experience the power of on-device AI in a fun puzzle format.',
    coverImage: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=300&fit=crop',
    tags: ['LLM Puzzle', 'Offline', 'Mobile', 'iOS', 'Riddles'],
    platform: ['iOS'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: '2UP Games',
    url: 'https://www.2up.games/',
    shortDescription: 'Multiplayer AI-powered games for two players.',
    fullDescription: '2UP Games offers multiplayer AI-powered gaming experiences designed for two players. Compete or cooperate with a friend in AI-driven game scenarios that create unique challenges every session.',
    coverImage: 'https://images.unsplash.com/photo-1535223289429-462ea9301402?w=400&h=300&fit=crop',
    tags: ['Multiplayer', '2 Player', 'AI Games', 'Competitive'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'AI Central',
    url: 'https://aigamecentral.com/',
    shortDescription: 'Central hub for discovering and playing AI games.',
    fullDescription: 'AI Game Central is a comprehensive hub for AI game discovery. Find the latest AI-powered games, read reviews, and access a growing library of browser-based and downloadable AI games.',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    tags: ['AI Games Hub', 'Discovery', 'Reviews'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Yodayo',
    url: 'https://yodayo.com/',
    shortDescription: 'AI-powered anime roleplay and character chat platform.',
    fullDescription: 'Yodayo is an AI-powered platform for anime fans featuring character roleplay, AI art generation, and community features. Chat with AI anime characters, create your own, and share with a passionate community.',
    coverImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=300&fit=crop',
    tags: ['Anime', 'AI Chat', 'Roleplay', 'AI Art', 'Community'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: true,
    featuredOrder: 9,
  },
  {
    title: 'Janitor AI',
    url: 'https://janitorai.com/',
    shortDescription: 'Chat with AI characters — create your own or explore community creations.',
    fullDescription: 'Janitor AI is a character AI chat platform where you can talk with thousands of AI characters created by the community. Create your own characters, customize personalities, and engage in immersive roleplay conversations.',
    coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=300&fit=crop',
    tags: ['AI Chat', 'Character Roleplay', 'Community', 'NSFW Optional'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Spicy Chat',
    url: 'https://spicychat.ai/',
    shortDescription: 'Engage in immersive AI character conversations with no filter.',
    fullDescription: 'SpicyChat AI offers unfiltered AI character conversations for adult users. Create custom AI personas, engage in creative roleplay, and explore a wide range of character types and scenarios.',
    coverImage: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=400&h=300&fit=crop',
    tags: ['AI Chat', 'Adult', 'Roleplay', 'Character AI'],
    platform: ['Web'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Crushon AI',
    url: 'https://crushon.ai/',
    shortDescription: 'Unfiltered AI character chat with immersive roleplay experiences.',
    fullDescription: 'CrushOn AI is an unfiltered AI character chat platform featuring thousands of characters for immersive roleplay. Engage in deep conversations, explore creative scenarios, and build relationships with AI companions.',
    coverImage: 'https://images.unsplash.com/photo-1535223289429-462ea9301402?w=400&h=300&fit=crop',
    tags: ['AI Chat', 'Roleplay', 'Companion', 'Unfiltered'],
    platform: ['Web', 'iOS', 'Android'],
    isFree: true,
    pricingNote: 'Free + Premium',
    featured: false,
    featuredOrder: null,
  },
  {
    title: 'Replika',
    url: 'https://replika.com/',
    shortDescription: 'Your AI companion — always here to listen and chat.',
    fullDescription: 'Replika is an AI companion app designed to be your personal friend. Have meaningful conversations, share your thoughts and feelings, and build a unique relationship with your AI companion that learns and grows with you.',
    coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop',
    tags: ['AI Companion', 'Mental Wellness', 'Chat', 'Relationship'],
    platform: ['Web', 'iOS', 'Android'],
    isFree: true,
    pricingNote: 'Free + Replika Pro',
    featured: true,
    featuredOrder: 10,
  },
]

async function main() {
  console.log('🌱 Starting to seed 50 AI games...')

  let created = 0
  let skipped = 0

  for (const game of games) {
    const baseSlug = slugify(game.title)
    let slug = baseSlug
    let attempt = 0

    // Handle slug conflicts
    while (true) {
      const existing = await prisma.game.findUnique({ where: { slug } })
      if (!existing) break
      attempt++
      slug = `${baseSlug}-${attempt}`
    }

    // Check for duplicate URL
    if (game.url) {
      const existingByUrl = await prisma.game.findFirst({ where: { url: game.url } })
      if (existingByUrl) {
        console.log(`  ⏭  Skipped (duplicate URL): ${game.title}`)
        skipped++
        continue
      }
    }

    const categorySlug = inferCategory(game.tags.join(' '), game.title)

    await prisma.game.create({
      data: {
        title: game.title,
        slug,
        url: game.url,
        shortDescription: game.shortDescription,
        fullDescription: game.fullDescription,
        coverImage: game.coverImage,
        categorySlug,
        status: ContentStatus.PUBLISHED,
        source: ContentSource.CRAWLER,
        tags: {
          create: game.tags.map((tagName) => ({
            tag: {
              connectOrCreate: {
                where: { name: tagName },
                create: { name: tagName },
              },
            },
          })),
        },
      },
    })

    console.log(`  ✅ Created: ${game.title} [${categorySlug}]`)
    created++
  }

  console.log(`\n🎉 Seed complete! Created: ${created}, Skipped: ${skipped}`)
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
