"use client";

import { useState, useRef, useEffect } from "react";
import { Send, Settings, Sparkles, AlertCircle, ChevronDown, Check, Coins, StopCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import { useChat } from 'ai/react';

const MODELS = [
  { id: "gpt-4o", name: "GPT-4o (Official)", type: "official", cost: 10, recommended: true },
  { id: "claude-3-5", name: "Claude 3.5 Sonnet", type: "official", cost: 15 },
  { id: "gemini-1-5", name: "Gemini 1.5 Pro", type: "official", cost: 12 },
  { id: "deepseek-custom", name: "DeepSeek (Custom Key)", type: "custom", cost: 0 },
];

export default function PlayPage({ params }: { params: { slug: string } }) {
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [selectedModel, setSelectedModel] = useState(MODELS[0]);
  const [isDisclaimerOpen, setIsDisclaimerOpen] = useState(true);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const chat = useChat({
    api: '/api/chat',
    body: {
      modelId: selectedModel.id,
    },
    initialMessages: [
      { id: "sys-0", role: "assistant", content: "Welcome to Neon Dreams. You find yourself in a dark alleyway, rain slicking the pavement. A neon sign buzzes overhead, casting long shadows. What do you do?" }
    ]
  });

  const { messages, input, handleInputChange, handleSubmit, isLoading, stop, setMessages } = chat as any;

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const onSend = (e: React.FormEvent<HTMLFormElement> | React.KeyboardEvent<HTMLTextAreaElement>) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;
    handleSubmit(e as React.FormEvent<HTMLFormElement>);
  };

  const handleInteractiveChoice = (choice: string) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    handleInputChange({ target: { value: choice } } as any);
    setTimeout(() => {
      // Create a synthetic event for handleSubmit
      const form = document.createElement('form');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      form.onsubmit = handleSubmit as any;
      form.dispatchEvent(new Event('submit', { cancelable: true, bubbles: true }));
    }, 0);
  };

  return (
    <div className="flex flex-col md:flex-row h-[calc(100vh-6rem)] -m-4 md:-m-8 md:mt-[-2rem] bg-black">
      
      {/* Left Column: Main Chat Area (Flex 1) */}
      <div className="flex-1 flex flex-col relative h-full border-r border-white/5 bg-background">
        
        {/* Background Image (Blurred) */}
        <div 
          className="absolute inset-0 bg-cover bg-center opacity-10 pointer-events-none"
          style={{ backgroundImage: `url(https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop)` }}
        />
        
        {/* Disclaimer Banner */}
        {isDisclaimerOpen && (
          <div className="bg-status-warning/10 border-b border-status-warning/20 p-2 md:p-3 flex items-start md:items-center justify-between z-10">
            <div className="flex items-center gap-2 text-status-warning text-xs md:text-sm">
              <AlertCircle className="w-4 h-4 flex-shrink-0" />
              <p>Disclaimer: Content is generated by AI. Do not blindly trust or encourage inappropriate generation.</p>
            </div>
            <button 
              onClick={() => setIsDisclaimerOpen(false)}
              className="text-status-warning/60 hover:text-status-warning transition-colors p-1"
            >
              &times;
            </button>
          </div>
        )}

        {/* Message List */}
        <div className="flex-1 overflow-y-auto p-4 md:p-6 space-y-6 z-10 no-scrollbar">
          {messages.map((msg: any, i: number) => (
            <div key={i} className={cn(
              "flex gap-4 max-w-[85%]",
              msg.role === "user" ? "ml-auto flex-row-reverse" : ""
            )}>
              {/* Avatar */}
              <div className={cn(
                "w-8 h-8 md:w-10 md:h-10 rounded-full flex items-center justify-center flex-shrink-0 shadow-lg",
                msg.role === "user" ? "bg-white/10" : "bg-gradient-primary"
              )}>
                {msg.role === "assistant" && <Sparkles className="w-4 h-4 md:w-5 md:h-5 text-white" />}
              </div>
              
              {/* Bubble */}
              <div className={cn(
                "px-4 md:px-5 py-3 md:py-4 rounded-2xl md:rounded-3xl shadow-sm text-sm md:text-base leading-relaxed whitespace-pre-wrap",
                msg.role === "user" 
                  ? "bg-white/10 text-white rounded-tr-sm border border-white/5" 
                  : "bg-background-elevated/80 backdrop-blur-sm text-text-primary rounded-tl-sm border border-white/5"
              )}>
                {msg.content}
                
                {/* Mock Interactive Options (only for assistant messages) */}
                {msg.role === "assistant" && i === messages.length - 1 && !isLoading && (
                  <div className="mt-4 flex flex-wrap gap-2">
                    <button onClick={() => handleInteractiveChoice("Look around")} className="px-3 py-1.5 text-xs font-medium rounded-lg bg-primary/20 text-primary border border-primary/30 hover:bg-primary/30 transition-colors">
                      Look around
                    </button>
                    <button onClick={() => handleInteractiveChoice("Check inventory")} className="px-3 py-1.5 text-xs font-medium rounded-lg bg-primary/20 text-primary border border-primary/30 hover:bg-primary/30 transition-colors">
                      Check inventory
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-4 md:p-6 bg-background-paper/90 backdrop-blur-md border-t border-white/5 z-10 relative">
          
          <form onSubmit={onSend} className="relative flex items-center bg-background-elevated border border-white/10 rounded-2xl focus-within:ring-2 ring-primary/50 transition-all p-1 md:p-2">
            
            {/* Model Selector Dropdown */}
            <div className="relative">
              <button 
                type="button"
                onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                className="flex items-center gap-1.5 md:gap-2 px-2 md:px-3 py-2 bg-transparent text-xs md:text-sm text-text-secondary hover:text-white transition-colors rounded-xl hover:bg-white/5"
              >
                <Sparkles className={cn("w-3.5 h-3.5 md:w-4 md:h-4", selectedModel.type === 'official' ? "text-primary" : "text-status-success")} />
                <span className="hidden sm:inline font-medium max-w-[100px] truncate">{selectedModel.name}</span>
                <ChevronDown className="w-3.5 h-3.5 md:w-4 md:h-4" />
              </button>

              {/* Dropdown Menu */}
              {isDropdownOpen && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setIsDropdownOpen(false)} />
                  <div className="absolute bottom-full left-0 mb-2 w-56 md:w-64 rounded-2xl bg-background-elevated border border-white/10 shadow-2xl overflow-hidden z-50 animate-in slide-in-from-bottom-2 duration-200">
                    <div className="p-1.5">
                      <div className="px-3 py-2 text-[10px] md:text-xs text-text-muted uppercase tracking-wider font-semibold">Official Models</div>
                      {MODELS.filter(m => m.type === 'official').map(model => (
                        <button
                          key={model.id}
                          type="button"
                          onClick={() => { setSelectedModel(model); setIsDropdownOpen(false); }}
                          className="w-full text-left px-3 py-2.5 text-xs md:text-sm text-text-primary hover:bg-white/5 rounded-xl flex items-center justify-between group transition-colors"
                        >
                          <div className="flex items-center gap-2">
                            {selectedModel.id === model.id ? <Check className="w-4 h-4 text-primary" /> : <div className="w-4 h-4" />}
                            <span className="font-medium">{model.name}</span>
                          </div>
                          <div className="flex items-center gap-1 text-status-warning/80 group-hover:text-status-warning">
                            <span className="text-xs">-{model.cost}</span>
                            <Coins className="w-3 h-3" />
                          </div>
                        </button>
                      ))}
                      
                      <div className="my-1.5 border-t border-white/5"></div>
                      
                      <div className="px-3 py-2 text-[10px] md:text-xs text-text-muted uppercase tracking-wider font-semibold">Custom Keys</div>
                      {MODELS.filter(m => m.type === 'custom').map(model => (
                        <button
                          key={model.id}
                          type="button"
                          onClick={() => { setSelectedModel(model); setIsDropdownOpen(false); }}
                          className="w-full text-left px-3 py-2.5 text-xs md:text-sm text-text-primary hover:bg-white/5 rounded-xl flex items-center justify-between group transition-colors"
                        >
                          <div className="flex items-center gap-2">
                            {selectedModel.id === model.id ? <Check className="w-4 h-4 text-status-success" /> : <div className="w-4 h-4" />}
                            <span className="font-medium">{model.name}</span>
                          </div>
                          <span className="text-[10px] md:text-xs text-status-success bg-status-success/10 px-2 py-0.5 rounded-md font-medium">Free</span>
                        </button>
                      ))}
                    </div>
                  </div>
                </>
              )}
            </div>

            <textarea
              value={input}
              onChange={handleInputChange}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  onSend(e);
                }
              }}
              placeholder={`Send a message to ${params.slug}...`}
              className="flex-1 bg-transparent border-none focus:ring-0 text-text-primary placeholder-text-muted text-sm md:text-base px-2 md:px-4 py-2 md:py-3 outline-none resize-none h-10 md:h-12 flex items-center"
            />
            
            {isLoading ? (
               <button 
                 type="button"
                 onClick={() => stop()}
                 className="p-2 md:p-3 mr-1 rounded-xl bg-status-error/20 text-status-error hover:bg-status-error/30 transition-all active:scale-95"
               >
                 <StopCircle className="w-4 h-4 md:w-5 md:h-5" />
               </button>
            ) : (
              <button 
                type="submit"
                disabled={!input.trim()}
                className="p-2 md:p-3 mr-1 rounded-xl bg-gradient-primary text-white disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-[0_0_15px_rgba(236,72,153,0.4)] transition-all active:scale-95"
              >
                <Send className="w-4 h-4 md:w-5 md:h-5" />
              </button>
            )}
          </form>
          
          <div className="text-center mt-3 text-[10px] md:text-xs text-text-muted font-medium">
            Shift + Enter to add a new line
          </div>
        </div>
      </div>

      {/* Right Column: Control Panel (Hidden on very small screens, 80 w on medium+) */}
      <div className="hidden md:flex flex-col w-80 lg:w-96 bg-background-paper border-l border-white/5 h-full overflow-y-auto no-scrollbar">
        {/* Info Header */}
        <div className="p-6 border-b border-white/5">
          <div className="flex items-center gap-4 mb-4">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img 
              src="https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=200&auto=format&fit=crop" 
              alt="Avatar" 
              className="w-16 h-16 rounded-2xl object-cover border border-white/10 shadow-lg"
            />
            <div>
              <h2 className="text-lg font-bold text-white mb-1">Neon Dreams</h2>
              <div className="flex gap-2">
                <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-md bg-white/5 text-text-secondary">RPG</span>
                <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-md bg-white/5 text-text-secondary">Cyberpunk</span>
              </div>
            </div>
          </div>
          
          <div className="flex justify-between text-sm text-text-muted mt-4 p-3 bg-white/5 rounded-xl border border-white/5">
            <div className="text-center">
              <div className="font-semibold text-white">12k</div>
              <div className="text-[10px] uppercase tracking-wider">Plays</div>
            </div>
            <div className="text-center">
              <div className="font-semibold text-status-warning">4.8</div>
              <div className="text-[10px] uppercase tracking-wider">Rating</div>
            </div>
            <div className="text-center">
              <div className="font-semibold text-white">Neon Studio</div>
              <div className="text-[10px] uppercase tracking-wider">Creator</div>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-white/5 px-2 pt-2">
          <button className="flex-1 pb-3 text-sm font-medium text-primary border-b-2 border-primary">Profile</button>
          <button className="flex-1 pb-3 text-sm font-medium text-text-secondary hover:text-text-primary transition-colors">Memory</button>
          <button className="flex-1 pb-3 text-sm font-medium text-text-secondary hover:text-text-primary transition-colors">Settings</button>
        </div>

        {/* Settings Content Mock */}
        <div className="p-6 space-y-6 flex-1">
          <div className="space-y-3">
            <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <Settings className="w-4 h-4 text-primary" /> Persona Masks
            </h3>
            <button className="w-full p-4 rounded-xl border border-dashed border-white/20 hover:border-primary/50 hover:bg-white/5 transition-all text-sm text-text-secondary flex items-center justify-center gap-2 font-medium">
              + Create New Persona
            </button>
          </div>

          <div className="space-y-3">
            <h3 className="text-sm font-bold text-white uppercase tracking-wider">Chat Settings</h3>
            <div className="p-1 bg-background-elevated rounded-xl border border-white/5">
              <button className="w-full text-left px-4 py-3 text-sm text-text-primary hover:bg-white/5 rounded-lg transition-colors font-medium">Start New Chat</button>
              <button className="w-full text-left px-4 py-3 text-sm text-text-primary hover:bg-white/5 rounded-lg transition-colors font-medium">Save Current Chat</button>
              <button className="w-full text-left px-4 py-3 text-sm text-text-primary hover:bg-white/5 rounded-lg transition-colors font-medium">View History</button>
            </div>
          </div>
          
          <div className="space-y-3">
            <h3 className="text-sm font-bold text-white uppercase tracking-wider">Appearance</h3>
            <div className="p-1 bg-background-elevated rounded-xl border border-white/5">
              <button className="w-full text-left px-4 py-3 text-sm text-text-primary hover:bg-white/5 rounded-lg transition-colors flex justify-between items-center font-medium">
                Blur Background
                <div className="w-8 h-4 bg-primary rounded-full relative shadow-[0_0_10px_rgba(139,92,246,0.5)]">
                  <div className="absolute right-1 top-0.5 w-3 h-3 bg-white rounded-full"></div>
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}