"use client";

import { useState, useRef, useEffect, useMemo } from "react";
import {
  Send,
  Settings,
  Sparkles,
  AlertCircle,
  ChevronDown,
  Check,
  Coins,
  StopCircle,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useChat } from "ai/react";
import type { Prisma } from "@prisma/client";

const MODELS = [
  { id: "gpt-4o", name: "GPT-4o (Official)", type: "official" as const, cost: 10, recommended: true },
  { id: "claude-3-5", name: "Claude 3.5 Sonnet", type: "official" as const, cost: 15 },
  { id: "gemini-1-5", name: "Gemini 1.5 Pro", type: "official" as const, cost: 12 },
  { id: "deepseek-custom", name: "DeepSeek (Custom Key)", type: "custom" as const, cost: 0 },
];

type TabId = "profile" | "memory" | "settings";

type PlayPageCharacter = Prisma.CharacterGetPayload<{
  include: { author: { select: { name: true } } };
}>;

export function PlayChatClient({
  slug,
  gameTitle,
  coverImage,
  categorySlug,
  playsLabel,
  rating,
  creatorName,
  character,
}: {
  slug: string;
  gameTitle: string;
  coverImage: string;
  categorySlug: string;
  playsLabel: string;
  rating: number;
  creatorName: string;
  character: PlayPageCharacter | null;
}) {
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [selectedModel, setSelectedModel] = useState(MODELS[0]);
  const [isDisclaimerOpen, setIsDisclaimerOpen] = useState(true);
  const [rightTab, setRightTab] = useState<TabId>("profile");
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const chatBody = useMemo(() => ({ modelId: selectedModel.id }), [selectedModel.id]);

  const initialMessages = useMemo(
    () => [
      {
        id: "sys-0",
        role: "assistant" as const,
        content: character?.greeting?.trim()
          ? character.greeting
          : `Welcome to ${gameTitle}. You find yourself at the start of an AI-driven story. What do you do?`,
      },
    ],
    [character?.greeting, gameTitle]
  );

  const chat = useChat({
    api: "/api/chat",
    body: chatBody,
    initialMessages,
  });

  const { messages, input, handleInputChange, handleSubmit, isLoading, stop, append } = chat;

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const onSend = (e: React.FormEvent<HTMLFormElement> | React.KeyboardEvent<HTMLTextAreaElement>) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;
    handleSubmit(e as React.FormEvent<HTMLFormElement>);
  };

  const handleInteractiveChoice = (choice: string) => {
    void append({ role: "user", content: choice });
  };

  return (
    <div className="flex flex-col md:flex-row h-[calc(100vh-6rem)] -m-4 md:-m-8 md:mt-[-2rem] bg-black">
      <div className="flex-1 flex flex-col relative h-full border-r border-white/5 bg-background">
        <div
          className="absolute inset-0 bg-cover bg-center opacity-10 pointer-events-none"
          style={{ backgroundImage: `url(${coverImage})` }}
        />

        {isDisclaimerOpen && (
          <div className="bg-status-warning/10 border-b border-status-warning/20 p-2 md:p-3 flex items-start md:items-center justify-between z-10">
            <div className="flex items-center gap-2 text-status-warning text-xs md:text-sm">
              <AlertCircle className="w-4 h-4 flex-shrink-0" />
              <p>
                Disclaimer: Content is generated by AI. Do not blindly trust or encourage inappropriate
                generation.
              </p>
            </div>
            <button
              type="button"
              onClick={() => setIsDisclaimerOpen(false)}
              className="text-status-warning/60 hover:text-status-warning transition-colors p-1"
            >
              &times;
            </button>
          </div>
        )}

        <div className="flex-1 overflow-y-auto p-4 md:p-6 space-y-6 z-10 no-scrollbar">
          {messages.map((msg, i) => (
            <div
              key={"id" in msg && msg.id ? String(msg.id) : i}
              className={cn(
                "flex gap-4 max-w-[85%]",
                msg.role === "user" ? "ml-auto flex-row-reverse" : ""
              )}
            >
              <div
                className={cn(
                  "w-8 h-8 md:w-10 md:h-10 rounded-full flex items-center justify-center flex-shrink-0 shadow-lg",
                  msg.role === "user" ? "bg-white/10" : "bg-gradient-primary"
                )}
              >
                {msg.role === "assistant" && (
                  <Sparkles className="w-4 h-4 md:w-5 md:h-5 text-white" />
                )}
              </div>

              <div
                className={cn(
                  "px-4 md:px-5 py-3 md:py-4 rounded-2xl md:rounded-3xl shadow-sm text-sm md:text-base leading-relaxed whitespace-pre-wrap",
                  msg.role === "user"
                    ? "bg-white/10 text-white rounded-tr-sm border border-white/5"
                    : "bg-background-elevated/80 backdrop-blur-sm text-text-primary rounded-tl-sm border border-white/5"
                )}
              >
                {msg.content}

                {msg.role === "assistant" && i === messages.length - 1 && !isLoading && (
                  <div className="mt-4 flex flex-wrap gap-2">
                    <button
                      type="button"
                      onClick={() => handleInteractiveChoice("Look around")}
                      className="px-3 py-1.5 text-xs font-medium rounded-lg bg-primary/20 text-primary border border-primary/30 hover:bg-primary/30 transition-colors"
                    >
                      Look around
                    </button>
                    <button
                      type="button"
                      onClick={() => handleInteractiveChoice("Check inventory")}
                      className="px-3 py-1.5 text-xs font-medium rounded-lg bg-primary/20 text-primary border border-primary/30 hover:bg-primary/30 transition-colors"
                    >
                      Check inventory
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>

        <div className="p-4 md:p-6 bg-background-paper/90 backdrop-blur-md border-t border-white/5 z-10 relative">
          <form
            onSubmit={onSend}
            className="relative flex items-center bg-background-elevated border border-white/10 rounded-2xl focus-within:ring-2 ring-primary/50 transition-all p-1 md:p-2"
          >
            <div className="relative">
              <button
                type="button"
                onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                className="flex items-center gap-1.5 md:gap-2 px-2 md:px-3 py-2 bg-transparent text-xs md:text-sm text-text-secondary hover:text-white transition-colors rounded-xl hover:bg-white/5"
              >
                <Sparkles
                  className={cn(
                    "w-3.5 h-3.5 md:w-4 md:h-4",
                    selectedModel.type === "official" ? "text-primary" : "text-status-success"
                  )}
                />
                <span className="hidden sm:inline font-medium max-w-[100px] truncate">
                  {selectedModel.name}
                </span>
                <ChevronDown className="w-3.5 h-3.5 md:w-4 md:h-4" />
              </button>

              {isDropdownOpen && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setIsDropdownOpen(false)} />
                  <div className="absolute bottom-full left-0 mb-2 w-56 md:w-64 rounded-2xl bg-background-elevated border border-white/10 shadow-2xl overflow-hidden z-50">
                    <div className="p-1.5">
                      <div className="px-3 py-2 text-[10px] md:text-xs text-text-muted uppercase tracking-wider font-semibold">
                        Official Models
                      </div>
                      {MODELS.filter((m) => m.type === "official").map((model) => (
                        <button
                          key={model.id}
                          type="button"
                          onClick={() => {
                            setSelectedModel(model);
                            setIsDropdownOpen(false);
                          }}
                          className="w-full text-left px-3 py-2.5 text-xs md:text-sm text-text-primary hover:bg-white/5 rounded-xl flex items-center justify-between"
                        >
                          <div className="flex items-center gap-2">
                            {selectedModel.id === model.id ? (
                              <Check className="w-4 h-4 text-primary" />
                            ) : (
                              <div className="w-4 h-4" />
                            )}
                            <span className="font-medium">{model.name}</span>
                          </div>
                          <div className="flex items-center gap-1 text-status-warning/80">
                            <span className="text-xs">-{model.cost}</span>
                            <Coins className="w-3 h-3" />
                          </div>
                        </button>
                      ))}
                      <div className="my-1.5 border-t border-white/5" />
                      <div className="px-3 py-2 text-[10px] md:text-xs text-text-muted uppercase tracking-wider font-semibold">
                        Custom Keys
                      </div>
                      {MODELS.filter((m) => m.type === "custom").map((model) => (
                        <button
                          key={model.id}
                          type="button"
                          onClick={() => {
                            setSelectedModel(model);
                            setIsDropdownOpen(false);
                          }}
                          className="w-full text-left px-3 py-2.5 text-xs md:text-sm text-text-primary hover:bg-white/5 rounded-xl flex items-center justify-between"
                        >
                          <div className="flex items-center gap-2">
                            {selectedModel.id === model.id ? (
                              <Check className="w-4 h-4 text-status-success" />
                            ) : (
                              <div className="w-4 h-4" />
                            )}
                            <span className="font-medium">{model.name}</span>
                          </div>
                          <span className="text-[10px] md:text-xs text-status-success bg-status-success/10 px-2 py-0.5 rounded-md font-medium">
                            Free
                          </span>
                        </button>
                      ))}
                    </div>
                  </div>
                </>
              )}
            </div>

            <textarea
              value={input}
              onChange={handleInputChange}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  onSend(e);
                }
              }}
              placeholder={`Send a message about ${slug}...`}
              className="flex-1 bg-transparent border-none focus:ring-0 text-text-primary placeholder-text-muted text-sm md:text-base px-2 md:px-4 py-2 md:py-3 outline-none resize-none min-h-10 md:min-h-12"
            />

            {isLoading ? (
              <button
                type="button"
                onClick={() => stop()}
                className="p-2 md:p-3 mr-1 rounded-xl bg-status-error/20 text-status-error hover:bg-status-error/30 transition-all active:scale-95"
              >
                <StopCircle className="w-4 h-4 md:w-5 md:h-5" />
              </button>
            ) : (
              <button
                type="submit"
                disabled={!input.trim()}
                className="p-2 md:p-3 mr-1 rounded-xl bg-gradient-primary text-white disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-[0_0_15px_rgba(236,72,153,0.4)] transition-all active:scale-95"
              >
                <Send className="w-4 h-4 md:w-5 md:h-5" />
              </button>
            )}
          </form>
          <div className="text-center mt-3 text-[10px] md:text-xs text-text-muted font-medium">
            Shift + Enter to add a new line
          </div>
        </div>
      </div>

      <div className="hidden md:flex flex-col w-80 lg:w-96 bg-background-paper border-l border-white/5 h-full overflow-y-auto no-scrollbar">
        <div className="p-6 border-b border-white/5">
          <div className="flex items-center gap-4 mb-4">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={coverImage}
              alt={gameTitle}
              className="w-16 h-16 rounded-2xl object-cover border border-white/10 shadow-lg"
            />
            <div>
              <h2 className="text-lg font-bold text-white mb-1">{gameTitle}</h2>
              <div className="flex gap-2 flex-wrap">
                <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-md bg-white/5 text-text-secondary">
                  {categorySlug}
                </span>
              </div>
            </div>
          </div>

          <div className="flex justify-between text-sm text-text-muted mt-4 p-3 bg-white/5 rounded-xl border border-white/5">
            <div className="text-center">
              <div className="font-semibold text-white">{playsLabel}</div>
              <div className="text-[10px] uppercase tracking-wider">Plays</div>
            </div>
            <div className="text-center">
              <div className="font-semibold text-status-warning">{rating}</div>
              <div className="text-[10px] uppercase tracking-wider">Rating</div>
            </div>
            <div className="text-center min-w-0">
              <div className="font-semibold text-white truncate max-w-[100px]">{creatorName}</div>
              <div className="text-[10px] uppercase tracking-wider">Creator</div>
            </div>
          </div>
        </div>

        <div className="flex border-b border-white/5 px-2 pt-2">
          {(["profile", "memory", "settings"] as TabId[]).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => setRightTab(t)}
              className={cn(
                "flex-1 pb-3 text-sm font-medium capitalize transition-colors",
                rightTab === t
                  ? "text-primary border-b-2 border-primary"
                  : "text-text-secondary hover:text-text-primary"
              )}
            >
              {t}
            </button>
          ))}
        </div>

        <div className="p-6 space-y-6 flex-1">
          {rightTab === "profile" && (
            <p className="text-sm text-text-secondary">
              Game context loaded from the database. Persona masks and memory are coming next.
            </p>
          )}
          {rightTab === "memory" && (
            <p className="text-sm text-text-secondary">Save and recall long-term memory for this session (planned).</p>
          )}
          {rightTab === "settings" && (
            <>
              <div className="space-y-3">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
                  <Settings className="w-4 h-4 text-primary" /> Persona Masks
                </h3>
                <button
                  type="button"
                  className="w-full p-4 rounded-xl border border-dashed border-white/20 hover:border-primary/50 hover:bg-white/5 transition-all text-sm text-text-secondary"
                >
                  + Create New Persona
                </button>
              </div>
              <div className="space-y-3">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider">Appearance</h3>
                <div className="p-1 bg-background-elevated rounded-xl border border-white/5">
                  <div className="w-full text-left px-4 py-3 text-sm text-text-primary flex justify-between items-center font-medium">
                    Blur Background
                    <div className="w-8 h-4 bg-primary rounded-full relative shadow-[0_0_10px_rgba(139,92,246,0.5)]">
                      <div className="absolute right-1 top-0.5 w-3 h-3 bg-white rounded-full" />
                    </div>
                  </div>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
